services:
  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - ./porstgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: graphql
      POSTGRES_PASSWORD: graphql
      POSTGRES_DB: graphql
